//Generated by tools/gen_protocol
package consts

type EquipLoadParams struct {
    PlayerID string
    EquipId string
    HeroId string
}

type EquipLoadResponse struct {
    PlayerID string
    EquipId string
    Level uint32
}

type EquipUnLoadParams struct {
    PlayerID string
    EquipId string
    HeroId string
}

type EquipUnLoadResponse struct {
    PlayerID string
    EquipId string
    Level uint32
}

type LoginResponse struct {
    Uuid string
    Level uint32
    Exp float32
    Equips []*EquipLoadResponse
    Friends []string
    Ages []int32
}
