/*
 * Generated by tools/gen_protocol
 */

package api

var NameToId = map[string]uint16{
    "EquipLoadParams": uint16(1),
    "EquipLoadResponse": uint16(2),
    "EquipUnLoadParams": uint16(3),
    "EquipUnLoadResponse": uint16(4),
    "LoginResponse": uint16(5)}

var IdToName = map[uint16]string{
    uint16(1): "EquipLoadParams",
    uint16(2): "EquipLoadResponse",
    uint16(3): "EquipUnLoadParams",
    uint16(4): "EquipUnLoadResponse",
    uint16(5): "LoginResponse"}
