development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gos_server_development
  pool: 5
  username: root
  password: ''

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gos_server_test
  pool: 5
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gos_server_production
  pool: 20
  username: root
  password: ''

