//Generated by generate_tables

package tables

import (
	. "app/consts"
	"github.com/go-gorp/gorp"
)

func RegisterTables(dbInstance *gorp.DbMap) {
	dbInstance.AddTableWithName(Equip{}, "equips").SetKeys(false, "uuid")
	dbInstance.AddTableWithName(User{}, "users").SetKeys(false, "uuid")

}
